name = "firmapp-credits-worker"
main = "cloudflare_worker.js"
compatibility_date = "2024-05-01"

[vars]
FIREBASE_PROJECT_ID = "firmapp-ad67f" 

[ai]
binding = "AI"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "firmapp-db"
database_id = "4a8609fb-2593-4d94-8123-39404470a159"
