class LocalizationService {
  static const Map<String, Map<String, String>> _data = {
    'es': {
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'ESCANEAR',
      'signature': 'Mis Firmas',
      'my_docs': 'Mis Documentos',
      'settings': 'Configuración',
      'quality_filter': 'Filtro de Calidad',
      'quality_desc': 'Avisa si la foto está oscura',
      'manual_crop': 'Recorte Manual',
      'crop_desc': 'Ajustar bordes después de escanear',
      'terms': 'Términos de Uso',
      'logout': 'Cerrar Sesión',
      'theme_title': 'Tema',
      'theme_light': 'Claro',
      'theme_dark': 'Modo',
      'language_label': 'Idioma',
      'help': 'Preguntas Frecuentes',
      'import': 'Importar JPG/PDF',
      'import_file': 'Importar Archivo',
      'delete': 'Borrar',
      'rename': 'Nombre',
      'share': 'Compartir',
      'ocr': 'OCR',
      'close': 'Cerrar',
      'loading_ad': 'Cargar',
      'free_credit': '+1 Gratis',
      'login_welcome': 'Bienvenido a FirmApp',
      'login_subtitle': 'Escanea y firma documentos profesionalmente',
      'login_enter': 'Ingresa a tu cuenta',
      'login_register': 'Regístrate gratis',
      'login_email': 'Email',
      'login_password': 'Contraseña',
      'login_name': 'Nombre Completo',
      'login_forgot': '¿Olvidaste tu clave?',
      'login_btn': 'INGRESAR',
      'login_create_btn': 'CREAR CUENTA',
      'login_no_account': '¿No tienes cuenta? Regístrate',
      'login_has_account': '¿Ya tienes cuenta? Ingresa',
      'login_or': 'O',
      'google_signin': 'CONTINUAR CON GOOGLE',
      'google_signup': 'REGISTRARSE CON GOOGLE',
      'faq_title': 'Preguntas Frecuentes',
      'sig_capture': 'Capturar Firma',
      'sig_canvas_desc': 'Firma en el recuadro o toma una foto',
      'sig_photo_btn': 'FIRMA EN PAPEL',
      'sig_clear': 'Limpiar',
      'sig_save': 'GUARDAR FIRMA',
      'import_sig': 'IMPORTAR FIRMA',
      'refine_title': 'Refinar Firma',
      'refine_l1': 'Mejorar Nitidez',
      'refine_l1_desc': 'Define el trazo (Local - Gratis)',
      'refine_l2': 'IA Worker (Nube)',
      'refine_l2_desc': 'Limpieza inteligente de sombras',
      'refine_l3': 'IA Premium (API Pago)',
      'refine_l3_desc': 'Calidad definitiva de estudio',
      'save_final': 'GUARDAR FIRMA FINAL',
      'no_credits': 'Sin créditos suficientes',
      'view': 'Visualizar',
      'sign': 'Firmar',
      'terms_title': 'Términos y Condiciones',
      'terms_s1_t': '1. Aceptación',
      'terms_s1_b': 'Al descargar o usar FirmApp, usted acepta estos términos. Si no está de acuerdo, no utilice la aplicación.',
      'terms_s2_t': '2. Licencia',
      'terms_s2_b': 'Se otorga una licencia limitada y no exclusiva para uso personal o profesional lícitos.',
      'terms_s3_t': '3. Naturaleza de las Firmas (Deslinde)',
      'terms_s3_b': 'IMPORTANTE: Las firmas generadas NO son firmas digitales certificadas (PKI). Son representaciones gráficas de una firma manuscrita. El usuario es responsable de validar su aceptación legal.',
      'terms_s4_t': '4. OCR y Escaneo',
      'terms_s4_b': 'El reconocimiento de texto es una herramienta de asistencia. No se garantiza precisión del 100%. Revise siempre los resultados.',
      'terms_s5_t': '5. Limitación de Responsabilidad',
      'terms_s5_b': 'El Autor no se hace responsable por daños derivados del uso incorrecto, pérdida de datos locales o fallos técnicos del dispositivo.',
      'terms_s6_t': '6. Propiedad Intelectual',
      'terms_s6_b': 'El código, diseño y logotipos son propiedad exclusiva del Autor. Prohibida la ingeniería inversa.',
      'terms_s7_t': '7. Créditos y Anuncios',
      'terms_s7_b': 'El uso de funciones avanzadas requiere créditos. Estos no tienen valor monetario y no son reembolsables.',
      'terms_s8_t': '8. Privacidad',
      'terms_s8_b': 'El procesamiento es local. Solo se transmiten datos cifrados si se solicita explícitamente el procesamiento de IA en la nube.',
      'terms_s9_t': '9. Ley Aplicable',
      'terms_s9_b': 'Estos términos se rigen por las leyes del país del Autor. El uso continuo implica la aceptación de modificaciones.',
    },
    'en': {
      'app_name': 'FirmApp',
      'credits': 'Credits',
      'scan': 'SCAN',
      'signature': 'My Signatures',
      'my_docs': 'My Documents',
      'settings': 'Settings',
      'quality_filter': 'Quality Filter',
      'quality_desc': 'Warn if photo is dark',
      'manual_crop': 'Manual Crop',
      'crop_desc': 'Adjust edges after scanning',
      'terms': 'Terms of Use',
      'logout': 'Log Out',
      'theme_title': 'Theme',
      'theme_light': 'Light',
      'theme_dark': 'Mode',
      'language_label': 'Language',
      'help': 'Help',
      'import': 'Import JPG/PDF',
      'import_file': 'Import File',
      'delete': 'Delete',
      'rename': 'Rename',
      'share': 'Share',
      'ocr': 'OCR',
      'close': 'Close',
      'loading_ad': 'Load',
      'free_credit': '+1 Free',
      'login_welcome': 'Welcome to FirmApp',
      'login_subtitle': 'Scan and sign documents professionally',
      'google_signin': 'Continue with Google',
      'google_signup': 'Sign up with Google',
      'faq_title': 'FAQ',
      'sig_capture': 'Capture Signature',
      'sig_canvas_desc': 'Sign in the box or take a photo',
      'sig_photo_btn': 'PAPER SIGNATURE',
      'sig_clear': 'Clear',
      'sig_save': 'SAVE SIGNATURE',
      'import_sig': 'IMPORT SIGNATURE',
      'refine_title': 'Refine Signature',
      'refine_l1': 'Improve Sharpness',
      'refine_l1_desc': 'Define the stroke (Local - Free)',
      'refine_l2': 'AI Worker (Cloud)',
      'refine_l2_desc': 'Smart shadow cleaning',
      'refine_l3': 'Premium AI (Paid)',
      'refine_l3_desc': 'Ultimate studio quality',
      'save_final': 'SAVE FINAL SIGNATURE',
      'no_credits': 'Not enough credits',
      'view': 'View',
      'sign': 'Sign',
      'terms_title': 'Terms and Conditions',
      'terms_s1_t': '1. Acceptance',
      'terms_s1_b': 'By downloading or using FirmApp, you agree to these terms. If you do not agree, do not use the application.',
      'terms_s2_t': '2. License',
      'terms_s2_b': 'A limited, non-exclusive license is granted for lawful personal or professional use.',
      'terms_s3_t': '3. Nature of Signatures (Disclaimer)',
      'terms_s3_b': 'IMPORTANT: Generated signatures are NOT certified digital signatures (PKI). They are graphic representations of a handwritten signature. User is responsible for legal validity.',
      'terms_s4_t': '4. OCR & Scanning',
      'terms_s4_b': 'Text recognition is an assistance tool. 100% accuracy is not guaranteed. Always review results.',
      'terms_s5_t': '5. Limitation of Liability',
      'terms_s5_b': 'The Author is not liable for damages resulting from misuse, local data loss, or technical device failures.',
      'terms_s6_t': '6. Intellectual Property',
      'terms_s6_b': 'Code, design, and logos are the exclusive property of the Author. Reverse engineering is prohibited.',
      'terms_s7_t': '7. Credits and Ads',
      'terms_s7_b': 'Advanced features require credits. Credits have no monetary value and are non-refundable.',
      'terms_s8_t': '8. Privacy',
      'terms_s8_b': 'Processing is local. Encrypted data is only transmitted if cloud AI processing is explicitly requested.',
      'terms_s9_t': '9. Governing Law',
      'terms_s9_b': 'These terms are governed by the laws of the Author\'s country. Continued use implies acceptance of modifications.',
    },
    'pt': {
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'ESCANEAR',
      'signature': 'ASSINAR',
      'my_docs': 'Meus Documentos',
      'settings': 'Configurações',
      'quality_filter': 'Filtro de Qualidade',
      'quality_desc': 'Avisa se a foto estiver escura',
      'manual_crop': 'Recorte Manual',
      'crop_desc': 'Ajustar bordas após escanear',
      'terms': 'Termos de Uso',
      'logout': 'Sair',
      'theme_title': 'Tema',
      'theme_light': 'Claro',
      'theme_dark': 'Escuro',
      'help': 'Ajuda',
      'import': 'Importar JPG/PDF',
      'delete': 'Excluir',
      'rename': 'Renomear',
      'share': 'Compartilhar',
      'ocr': 'OCR',
      'close': 'Fechar',
      'loading_ad': 'Carregar',
      'free_credit': '+1 Grátis',
      'login_welcome': 'Bem-vindo ao FirmApp',
      'login_subtitle': 'Digitalize e assine documentos profissionalmente',
      'google_signin': 'Continuar com Google',
      'faq_title': 'Perguntas Frequentes',
      'sig_capture': 'Capturar Assinatura',
      'sig_canvas_desc': 'Assine no quadro ou tire uma foto',
      'sig_photo_btn': 'TIRAR FOTO DA ASSINATURA NO PAPEL',
      'sig_clear': 'Limpar',
      'sig_save': 'Salvar',
      'refine_title': 'Refinar Assinatura',
      'refine_l1': 'Melhorar Nitidez',
      'refine_l1_desc': 'Define o traço (Local - Grátis)',
      'refine_l2': 'IA Worker (Nuvem)',
      'refine_l2_desc': 'Limpeza inteligente de sombras',
      'refine_l3': 'IA Premium (Paga)',
      'refine_l3_desc': 'Qualidade definitiva de estúdio',
      'save_final': 'SALVAR ASSINATURA FINAL',
      'no_credits': 'Créditos insuficientes',
      'terms_title': 'Termos e Condições',
      'terms_s1_t': '1. Aceitação',
      'terms_s1_b': 'Ao baixar ou usar o FirmaFácil, você concorda com estes termos. Se não concordar, não use o aplicativo.',
      'terms_s2_t': '2. Licença',
      'terms_s2_b': 'É concedida uma licença limitada e não exclusiva para uso pessoal ou profissional lícito.',
      'terms_s3_t': '3. Natureza das Assinaturas (Isenção)',
      'terms_s3_b': 'IMPORTANTE: As assinaturas geradas NÃO são assinaturas digitais certificadas (PKI). São representações gráficas de uma assinatura manuscrita.',
      'terms_s4_t': '4. OCR e Digitalização',
      'terms_s4_b': 'O reconhecimento de texto é uma ferramenta de assistência. A precisão de 100% não é garantida. Revise sempre os resultados.',
      'terms_s5_t': '5. Limitação de Responsabilidade',
      'terms_s5_b': 'O Autor não é responsável por danos decorrentes de uso indevido, perda de dados locais ou falhas técnicas do dispositivo.',
      'terms_s6_t': '6. Propriedade Intelectual',
      'terms_s6_b': 'O código, design e logotipos são propriedade exclusiva do Autor. A engenharia reversa é proibida.',
      'terms_s7_t': '7. Créditos e Anúncios',
      'terms_s7_b': 'O uso de funções avançadas requer créditos. Os créditos não têm valor monetário e não são reembolsáveis.',
      'terms_s8_t': '8. Privacidade',
      'terms_s8_b': 'O processamento é local. Dados criptografados só são transmitidos se o processamento de IA na nuvem for solicitado.',
      'terms_s9_t': '9. Lei Aplicável',
      'terms_s9_b': 'Estes termos são regidos pelas leis do país do Autor. O uso contínuo implica a aceitação de modificações.',
    },
    'fr': {
      'app_name': 'FirmApp',
      'credits': 'Crédits',
      'scan': 'SCANNER',
      'signature': 'SIGNER',
      'my_docs': 'Mes Documents',
      'settings': 'Paramètres',
      'quality_filter': 'Filtre de Qualité',
      'quality_desc': 'Alerte si la photo est sombre',
      'manual_crop': 'Recadrage Manuel',
      'crop_desc': 'Ajuster les bords après scan',
      'terms': 'Conditions d\'utilisation',
      'logout': 'Déconnexion',
      'theme_title': 'Thème',
      'theme_light': 'Clair',
      'theme_dark': 'Sombre',
      'help': 'Aide',
      'import': 'Importer JPG/PDF',
      'delete': 'Supprimer',
      'rename': 'Renommer',
      'share': 'Partager',
      'ocr': 'OCR',
      'close': 'Fermer',
      'loading_ad': 'Charger',
      'free_credit': '+1 Gratuit',
      'login_welcome': 'Bienvenue sur FirmApp',
      'login_subtitle': 'Numérisez et signez des documents professionnellement',
      'google_signin': 'Continuer avec Google',
      'faq_title': 'FAQ',
      'sig_capture': 'Capturer la Signature',
      'sig_canvas_desc': 'Signez dans la case ou prenez une photo',
      'sig_photo_btn': 'PRENDRE UNE PHOTO DE LA SIGNATURE',
      'sig_clear': 'Effacer',
      'sig_save': 'Enregistrer',
      'refine_title': 'Affiner la Signature',
      'refine_l1': 'Améliorer la Netteté',
      'refine_l1_desc': 'Définir le trait (Local - Gratuit)',
      'refine_l2': 'IA Worker (Cloud)',
      'refine_l2_desc': 'Nettoyage intelligent des ombres',
      'refine_l3': 'IA Premium (Payant)',
      'refine_l3_desc': 'Qualité studio ultime',
      'save_final': 'ENREGISTRER LA SIGNATURE FINALE',
      'no_credits': 'Crédits insuffisants',
      'terms_title': 'Conditions Générales',
      'terms_s1_t': '1. Acceptation',
      'terms_s1_b': 'En téléchargeant ou en utilisant SignerFacile, vous acceptez ces conditions. Si vous n\'êtes pas d\'accord, n\'utilisez pas l\'application.',
      'terms_s2_t': '2. Licence',
      'terms_s2_b': 'Une licence limitée et non exclusive est accordée pour un usage personnel ou professionnel licite.',
      'terms_s3_t': '3. Nature des Signatures (Avis)',
      'terms_s3_b': 'IMPORTANT: Les signatures générées ne sont PAS des signatures numériques certifiées (PKI). Ce sont des représentations graphiques d\'une signature manuscrite.',
      'terms_s4_t': '4. OCR & Numérisation',
      'terms_s4_b': 'La reconnaissance de texte est un outil d\'assistance. Une précision de 100% n\'est pas garantie. Vérifiez toujours les résultats.',
      'terms_s5_t': '5. Limitation de Responsabilité',
      'terms_s5_b': 'L\'Auteur n\'est pas responsable des dommages résultant d\'une mauvaise utilisation, de la perte de données locales ou de défaillances techniques de l\'appareil.',
      'terms_s6_t': '6. Propriété Intellectuelle',
      'terms_s6_b': 'Le code, le design et les logos sont la propriété exclusive de l\'Auteur. L\'ingénierie inverse est interdite.',
      'terms_s7_t': '7. Crédits et Publicités',
      'terms_s7_b': 'L\'utilisation de fonctionnalités avancées nécessite des crédits. Les crédits n\'ont aucune valeur monétaire et ne sont pas remboursables.',
      'terms_s8_t': '8. Confidentialité',
      'terms_s8_b': 'Le traitement est local. Les données cryptées ne sont transmises que si le traitement IA cloud est explicitement demandé.',
      'terms_s9_t': '9. Loi Applicable',
      'terms_s9_b': 'Ces conditions sont régies par les lois du pays de l\'Auteur. L\'utilisation continue implique l\'acceptation des modifications.',
    },
    'gn': { // Guaraní
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'MOHA\'ÃNGARERA',
      'signature': 'HERAGUAPY',
      'my_docs': 'Che Kuatiañe\'ẽnguéra',
      'settings': 'Ñemoporãmbýra',
      'quality_filter': 'Mbohovake Porã',
      'quality_desc': 'He\'i ndéve iñypytũramo',
      'manual_crop': 'Kytĩ Po rupi',
      'crop_desc': 'Embopora ijerére',
      'terms': 'Términos de Uso',
      'logout': 'Sẽ',
      'theme_title': 'Tema',
      'theme_light': 'Hendy',
      'theme_dark': 'Pytũ',
      'help': 'Pytyvõ',
      'import': 'Gueru JPG/PDF',
      'delete': 'Mbogue',
      'rename': 'Téra',
      'share': 'Moherakuã',
      'ocr': 'OCR',
      'close': 'Mboty',
      'loading_ad': 'Myanyhy',
      'free_credit': '+1 Gratis',
      'login_welcome': 'Maiteipa FirmApp-pe',
      'login_subtitle': 'Embokuatia ha emboheraguapy porã',
      'google_signin': 'Eike Google ndive',
      'faq_title': 'Porandu Meméva',
      'sig_capture': 'Ejapo Heraguapy',
      'sig_canvas_desc': 'Ehai ko\'ápe térã eipyhy peteĩ ta\'anga',
      'sig_photo_btn': 'EIPYHY TA\'ANGA KUATIA REHEGUA',
      'sig_clear': 'Potĩ',
      'sig_save': 'Ñongatu',
      'refine_title': 'Emboporã Heraguapy',
      'refine_l1': 'Haimbe\'e Porã',
      'refine_l1_desc': 'Embopora haimbe (Local - Gratis)',
      'refine_l2': 'IA Worker (Nube)',
      'refine_l2_desc': 'Emopotĩ iñypytũramo',
      'refine_l3': 'IA Premium (API Pago)',
      'refine_l3_desc': 'Iporãveva opaite mba\'égui',
      'save_final': 'ÑONGATU HERAGUAPY PAHA',
      'no_credits': 'Neresuficiéntei crédito',
      'terms_title': 'Términos de Uso',
      'terms_s1_t': '1. Ñemoneĩ',
      'terms_s1_b': 'Eipurúramo FirmApp, emoneĩ ko\'ã mba\'e. Tla ndereipotái, ani eipuru.',
      'terms_s2_t': '2. Licencia',
      'terms_s2_b': 'Oñeme\'ẽ ndéve peteĩ licencia eipuru hag̃ua ne pumbyrýpe.',
      'terms_s3_t': '3. Heraguapy tee (Disclaimer)',
      'terms_s3_b': 'IMPORTANTE: Ko\'ãva ndaha\'éi heraguapy digital (PKI). Ha\'e ta\'anga kuatiagua hína. Nde ha\'e responsable ne firma rehe.',
      'terms_s4_t': '4. OCR ha Escaneo',
      'terms_s4_b': 'OCR ha\'e peteĩ pytyvõ. Ndaipóri garantía 100% porãva.',
      'terms_s5_t': '5. Responsabilidad',
      'terms_s5_b': 'Ko app ojapova\'ekue ndaha\'éi jepytaso mba\'eveichagua ojavyramo térã okañýramo ne kuatia.',
      'terms_s6_t': '6. Propiedad Intelectual',
      'terms_s6_b': 'Opaite mba\'e ha\'e Autor mba\'e tee.',
      'terms_s7_t': '7. Créditos',
      'terms_s7_b': 'Eipuru hag̃ua funciones ipu\'akáva reikotevẽ crédito rehe.',
      'terms_s8_t': '8. Ñemimby',
      'terms_s8_b': 'Opaite mba\'e ojejapo ne pumbyrýpe (local).',
      'terms_s9_t': '9. Ley Aplicable',
      'terms_s9_b': 'Ko\'ã términos ikatu oñemoambue ára ohasávo.',
    },
    'qu': { // Quechua (Andino)
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'QHAWAY',
      'signature': 'SIKLLAY',
      'my_docs': 'Qillqaykuna',
      'settings': 'Allichaykuna',
      'quality_filter': 'Kusa Kay',
      'quality_desc': 'Willay laqha kaptin',
      'manual_crop': 'Kikiy kytĩ',
      'crop_desc': 'Bordeskunata allichay',
      'terms': 'Kamachiykuna',
      'logout': 'Lluqsiy',
      'theme_title': 'Tema',
      'theme_light': 'K’anchay',
      'theme_dark': 'Laqha',
      'help': 'Yanapay',
      'import': 'Apamuy JPG/PDF',
      'delete': 'Pichay',
      'rename': 'Suti',
      'share': 'Willay',
      'ocr': 'OCR',
      'close': 'Wichqay',
      'loading_ad': 'Churay',
      'free_credit': '+1 Gratis',
      'login_welcome': 'Allin hamusqay FirmApp-man',
      'login_subtitle': 'Qillqaykunata sumaqta firmanaykipaq',
      'google_signin': 'Google-wan qallariy',
      'faq_title': 'Tapukuykuna',
      'sig_capture': 'Firma hapiy',
      'sig_canvas_desc': 'Kaypi qillqay utaq ta\'angata eipyhy',
      'sig_photo_btn': 'PAPELPI FIRMATA QHAWAY',
      'sig_clear': 'Pichay',
      'sig_save': 'Waqaychay',
      'refine_title': 'Firmata allichay',
      'refine_l1': 'Kusa Haimbe',
      'refine_l1_desc': 'Allin qaway (Local - Gratis)',
      'refine_l2': 'IA Worker (Nube)',
      'refine_l2_desc': 'Llantukunata pichay',
      'refine_l3': 'IA Premium (API Pago)',
      'refine_l3_desc': 'Lliwmantapas aswan kusa',
      'save_final': 'TUKUPAY FIRMATA WAQAYCHAY',
      'no_credits': 'Mana créditos kanchu',
      'terms_title': 'Kamachiykuna',
      'terms_s1_t': '1. Ari niy',
      'terms_s1_b': 'FirmApp-ta eipurúramo, kayta ari ninki. Mana munaspaqa, ama eipuruychu.',
      'terms_s2_t': '2. Licencia',
      'terms_s2_b': 'Sumaq licencia qosqa celularniykipi eipurunaykipaq.',
      'terms_s3_t': '3. Sikllay Kay (Disclaimer)',
      'terms_s3_b': 'IMPORTANTE: Kaykunaqa manam digital certificasqachu (PKI). Qillqasqa kaqkunallam. Qanmi responsable kanki.',
      'terms_s4_t': '4. OCR hinaspa Qhañay',
      'terms_s4_b': 'OCR yanapayllapaqmi. Mana 100% sumaqchu kanman.',
      'terms_s5_t': '5. Limitación de Responsabilidad',
      'terms_s5_b': 'Ruwaqqa manam juchayuqchu pantay kaptin utaq qillqaykuna chinkaptin.',
      'terms_s6_t': '6. Propiedad Intelectual',
      'terms_s6_b': 'Tukuy imapas Ruwaqpa kapuyninmi.',
      'terms_s7_t': '7. Créditos',
      'terms_s7_b': 'Créditos nisqata necesitanki funciones avanzadapaq.',
      'terms_s8_t': '8. Ñemimby',
      'terms_s8_b': 'Tukuy imapas celularniykillapi ruwakun.',
      'terms_s9_t': '9. Kamachiykuna',
      'terms_s9_b': 'Kay kamachiykunaqa hukmanman tukunmanmi.',
    },
    'ay': { // Aymara
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'UÑACHAÑA',
      'signature': 'FIRMAÑA',
      'my_docs': 'Qillqatanaka',
      'settings': 'Askiñchaña',
      'quality_filter': 'Kusa Uñachaña',
      'quality_desc': 'Ch\'amakt\'atawa',
      'manual_crop': 'Amparampi khuchuñä',
      'crop_desc': 'Kusa asiriñchaña',
      'terms': 'Kamachinaka',
      'logout': 'Mistsuña',
      'theme_title': 'Tema',
      'theme_light': 'Qhana',
      'theme_dark': 'Ch\'amaka',
      'help': 'Yanapañä',
      'import': 'Aptanïña JPG/PDF',
      'delete': 'Pichaña',
      'rename': 'Suti',
      'share': 'Yatiyañä',
      'ocr': 'OCR',
      'close': 'Jist\'antañä',
      'loading_ad': 'Phuqt\'ayañä',
      'free_credit': '+1 Gratis',
      'login_welcome': 'Waliki purini FirmApp-man',
      'login_subtitle': 'Qillqatanaka kusa firmañataki',
      'google_signin': 'Google-mpi qalltañä',
      'faq_title': 'Jiskt\'anaka',
      'sig_capture': 'Firma katurañä',
      'sig_canvas_desc': 'Akaru qillqañä jan ukax ta\'anga eipyhy',
      'sig_photo_btn': 'PAPELAN FIRMA UÑACHAÑA',
      'sig_clear': 'Pichaña',
      'sig_save': 'Imañä',
      'refine_title': 'Firma askiñchaña',
      'refine_l1': 'Kusa Uñacht\'ayañä',
      'refine_l1_desc': 'Aski qaway (Local - Gratis)',
      'refine_l2': 'IA Worker (Nube)',
      'refine_l2_desc': 'Ch\'amakt\'at pichaña',
      'refine_l3': 'IA Premium (API Pago)',
      'refine_l3_desc': 'Lliwmantapas kusa',
      'save_final': 'TUKUPAY FIRMA IMAÑÄ',
      'no_credits': 'Janiw créditos utjkiti',
      'terms_title': 'Kamachinaka',
      'terms_s1_t': '1. Iyawa sañä',
      'terms_s1_b': 'FirmApp eipurúramo, iyawa sätawa. Jani munaspaqa, jan eipurumti.',
      'terms_s2_t': '2. Licencia',
      'terms_s2_b': 'Licencia qillqata celularaman lurasi.',
      'terms_s3_t': '3. Firmaña Kay (Disclaimer)',
      'terms_s3_b': 'IMPORTANTE: Janiwa digital certificasqakiti (PKI). Qillqatanakallawa. Jumawa responsable kanta.',
      'terms_s4_t': '4. OCR hinaspa Uñachaña',
      'terms_s4_b': 'OCR yanapañatakiwa. Janiwa 100% kuskäkiti.',
      'terms_s5_t': '5. Responsabilidad',
      'terms_s5_b': 'Luriri janiw juchanikiti pantay utjchi ukhax jan ukax qillqatanaka chinkchi ukhax.',
      'terms_s6_t': '6. Propiedad Intelectual',
      'terms_s6_b': 'Tukuy imas Luririta kapuyninawa.',
      'terms_s7_t': '7. Créditos',
      'terms_s7_b': 'Créditos yanapañataki funciones avanzadas.',
      'terms_s8_t': '8. Ñemimby',
      'terms_s8_b': 'Tukuy imas celularakipan lurasi.',
      'terms_s9_t': '9. Kamachinaka',
      'terms_s9_b': 'Aka kamachinaka mayjt\'ayatarispawa.',
    },
    'na': { // Náhuatl (México)
      'app_name': 'FirmApp',
      'credits': 'Créditos',
      'scan': 'TLAMACHIHUANI',
      'signature': 'TOCHICAHUAC',
      'my_docs': 'Noamatl',
      'settings': 'Tlayecoltiliztli',
      'quality_filter': 'Kuali Tlachiyani',
      'quality_desc': 'Tequiti tla tlayohua',
      'manual_crop': 'Tlayecoltilli',
      'crop_desc': 'Xictequi kuali',
      'terms': 'Tlanahuatilli',
      'logout': 'Xiquiza',
      'theme_title': 'Tema',
      'theme_light': 'Claro',
      'theme_dark': 'Oscuro',
      'help': 'Tlapalehuiliztli',
      'import': 'Xicuica JPG/PDF',
      'delete': 'Xicpohpolo',
      'rename': 'Tocaitl',
      'share': 'Xicmotehui',
      'ocr': 'OCR',
      'close': 'Xictzacu',
      'loading_ad': 'Xictemilti',
      'free_credit': '+1 Gratis',
      'login_welcome': 'Ximopanoti FirmApp',
      'login_subtitle': 'Xicfirma kuali moamatl',
      'google_signin': 'Xicueyili Google',
      'faq_title': 'Tlatlaniliztli',
      'sig_capture': 'Xicquixti Tochica',
      'sig_canvas_desc': 'Xihcuilo nican noso xicpacho',
      'sig_photo_btn': 'XICPACHO AMATL ITECHPA TOCHICA',
      'sig_clear': 'Xicchipahua',
      'sig_save': 'Xicpiya',
      'refine_title': 'Xicyecolti Tochica',
      'refine_l1': 'Kuali Tlachiyalli',
      'refine_l1_desc': 'Kuali (Local - Gratis)',
      'refine_l2': 'IA Worker (Nube)',
      'refine_l2_desc': 'Xicpohpolo ecahuilli',
      'refine_l3': 'IA Premium (API Pago)',
      'refine_l3_desc': 'Kualtzin opaite',
      'save_final': 'XICPIYA TOCHICA PAHA',
      'no_credits': 'Ahmo créditos',
      'terms_title': 'Tlanahuatilli',
      'terms_s1_t': '1. Tlanahuatilli',
      'terms_s1_b': 'Tla tiquihcuiloa FirmApp, tiquimonequiltia tlanahuatilli. Tla ahmo, ahmo xicueyili.',
      'terms_s2_t': '2. Licencia',
      'terms_s2_b': 'Licencia mocelular tlayecoltiliztli.',
      'terms_s3_t': '3. Tochica (Disclaimer)',
      'terms_s3_b': 'IMPORTANTE: Ahmo digital certificadas (PKI). Tochica amatl. Tehuatl tiresponsable.',
      'terms_s4_t': '4. OCR huan Tlamachihuani',
      'terms_s4_b': 'OCR tlapalehuiliztli. Ahmo 100% kuali.',
      'terms_s5_t': '5. Tlanahuatilli Responsabilidad',
      'terms_s5_b': 'Ahmo juchayo tla ahmo kuali noso moamatl polihui.',
      'terms_s6_t': '6. Propiedad Intelectual',
      'terms_s6_b': 'Mochi Autor icapuhuin.',
      'terms_s7_t': '7. Créditos',
      'terms_s7_b': 'Tiquimonequiltia créditos tlayecoltiliztli.',
      'terms_s8_t': '8. Ñemimby',
      'terms_s8_b': 'Moamatl mochiuhtoc mocelular.',
      'terms_s9_t': '9. Tlanahuatilli',
      'terms_s9_b': 'Tlanahuatilli ikatu oñemoambue.',
    }
  };

  static String translate(String key, String locale) {
    return _data[locale]?[key] ?? _data['es']![key]!;
  }
}
